               ┌───────────────────────────────┐
               │           CLIENT              │
               │  (мобильное приложение)       │
               └───────────────┬─────────── ───┘
                               │ 1. пользователь открыл приложение
                               ▼
               ┌───────────────────────────────┐
               │       LOAD BALANCER           │
               └───────────────┬──────────── ──┘
                               │ 2. балансировка запроса
                               ▼
┌──────────────────────────────────────────────────────── ───┐
│                   API GATEWAY                              │
│  + AuthServer / ServiceRegistry                            │
└───────────────┬───────────────┬───────────────┬───────────┘
                │               │               │
      3. проверка токена     4. запрос к SR    6. перенаправление
                ▼               ▼               ▼
         ┌───────────┐   ┌────────  ─────┐ ┌──────────── ─┐
         │ AuthServer│   │ServiceRegistry│ │ USER SERVICE │
         │  (JWT +   │   │   (IP lookup) │ │   (DB+Redis) │
         │  Redis)   │   └──────  ───────┘ └─────┬───── ──┘
         └───────────┘                         │
                                               │
                  ┌────────────────────────────┴────────────────── ───┐
                  │                 OTHER SERVICES                    │
                  │       (Order, Cart, Catalog, DB, ElasticSearch)   │
                  └───────────────┬──────────────────────┬────────────┘
                                  │ 10. событие "заказ не оформлен"
                                  ▼
                           ┌──────────── ───┐
                           │ MESSAGE BROKER │
                           │   (Kafka + DLQ)│
                           └─────┬──── ─────┘
                                 │ 11. уведомление о событии
                                 ▼
                        ┌─────────────────── ──┐
                        │ NOTIFICATION SERVICE │
                        │  подписан на топик   │
                        └─────────┬──────── ───┘
                                  │ 12. получить pushtoken из Redis
                                  ▼
                        ┌─────────────────────┐
                        │  DELIVERY WORKERS   │
                        └─────────┬───────────┘
                                  │ 13. HTTP запрос к Push Provider
                                  ▼
                        ┌─────────────────────┐
                        │     PUSH PROVIDER   │
                        └─────────┬───────────┘
                                  │ 14. если ошибка → DLQ
                                  │ 15. если ок → push на устройство
                                  ▼
                               [USER DEVICE]
